# Generated by Django 6.0.4 on 2026-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='photo_preuve',
            field=models.ImageField(blank=True, null=True, upload_to='preuves/'),
        ),
    ]
