# Generated by Django 6.0.4 on 2026-05-03 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mission_photo_preuve'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('distance_reference', models.FloatField(help_text='Distance en KM depuis le centre logistique')),
            ],
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='description_objet',
            new_name='adresse_precise',
        ),
        migrations.RemoveField(
            model_name='acheteur',
            name='landmarks',
        ),
        migrations.RemoveField(
            model_name='acheteur',
            name='note_vocale',
        ),
        migrations.RemoveField(
            model_name='livreur',
            name='biometrie_hash',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='date_commande',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='date_ajout',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='vendeur',
            name='commission',
        ),
        migrations.AddField(
            model_name='mission',
            name='prix_livraison',
            field=models.DecimalField(decimal_places=2, default=200, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='vendeur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='mission',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_acceptees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mission',
            name='statut',
            field=models.CharField(default='attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='utilisateur_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='utilisateur_set_permissions', to='auth.permission'),
        ),
        migrations.AddField(
            model_name='mission',
            name='ville_arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrivees', to='api.ville'),
        ),
        migrations.AddField(
            model_name='mission',
            name='ville_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departs', to='api.ville'),
        ),
    ]
