# Generated by Django 6.0.4 on 2026-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ville_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='note_vocale',
            field=models.FileField(blank=True, null=True, upload_to='vocaux/'),
        ),
    ]
