# Generated by Django 6.0.4 on 2026-06-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_wallet_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('DEPOT', 'Dépôt Mobile Money'), ('RETRAIT', 'Retrait Mobile Money'), ('GAIN_LIVRAISON', 'Gain de Livraison'), ('COMMISSION', 'Commission Application'), ('REMBOURSEMENT', 'Remboursement Client'), ('LITIGE', 'Litige / Course Bloquée')], max_length=20),
        ),
    ]
