# Generated by Django 6.0.4 on 2026-06-19 01:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_transaction_type_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='produit',
            name='mis_a_jour_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_solde',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='ville',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='api.ville'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_externe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
