# Generated by Django 6.0.4 on 2026-06-20 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_conversationcommande_messagechat'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='commande',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='api.commande'),
        ),
        migrations.AddField(
            model_name='mission',
            name='position_livreur_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='position_livreur_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='position_mise_a_jour_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ville',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
