# Generated by Django 6.0.4 on 2026-06-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_mission_commande_mission_position_livreur_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='date_commande',
            new_name='cree_le',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='quantite',
        ),
        migrations.AddField(
            model_name='commande',
            name='mis_a_jour_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='note_donnee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='otp',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='ville_arrivee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_arrivee', to='api.ville'),
        ),
        migrations.AddField(
            model_name='commande',
            name='ville_depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commandes_depart', to='api.ville'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='acheteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='api.acheteur'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente de paiement'), ('finance', 'Financée (en escrow)'), ('en_livraison', 'En livraison'), ('livre', 'Livrée'), ('decaisse', 'Décaissée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type_transaction',
            field=models.CharField(choices=[('DEPOT', 'Dépôt Mobile Money'), ('RETRAIT', 'Retrait Mobile Money'), ('ESCROW', 'Mise en Escrow (Commande Financée)'), ('GAIN_LIVRAISON', 'Gain de Livraison'), ('COMMISSION', 'Commission Application'), ('REMBOURSEMENT', 'Remboursement Client'), ('LITIGE', 'Litige / Course Bloquée')], max_length=20),
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='api.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
            ],
        ),
    ]
