# Generated by Django 5.2.3 on 2026-06-27 07:05
#
# Restructure ConversationCommande : passe d'une conversation
# groupée unique par commande (OneToOneField + ManyToManyField
# participants, qui mélangeait acheteur/vendeur/livreur dans le même
# fil) à des conversations privées par PAIRE de participants. Aucune
# vraie conversation n'existe encore en production à ce stade — on
# repart proprement plutôt que de migrer des données de test.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_clean_orphan_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Supprime les anciens messages et conversations de test
        migrations.RunSQL(
            "DELETE FROM api_messagechat;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DELETE FROM api_conversationcommande_participants;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DELETE FROM api_conversationcommande;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.RemoveField(
            model_name='conversationcommande',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='conversationcommande',
            name='commande',
        ),
        migrations.AddField(
            model_name='conversationcommande',
            name='commande',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE,
                related_name='conversations', to='api.commande',
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationcommande',
            name='participant_a',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE,
                related_name='conversations_a', to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversationcommande',
            name='participant_b',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE,
                related_name='conversations_b', to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='conversationcommande',
            constraint=models.UniqueConstraint(
                fields=('commande', 'participant_a', 'participant_b'),
                name='unique_conversation_par_paire',
            ),
        ),
    ]

