# Generated by Django 5.2.3 on 2026-06-27 07:05
#
# Restructure ConversationCommande : passe d'une conversation
# groupée unique par commande (OneToOneField + ManyToManyField
# participants, qui mélangeait acheteur/vendeur/livreur dans le même
# fil) à des conversations privées par PAIRE de participants. Aucune
# vraie conversation n'existe encore en production à ce stade — on
# repart proprement plutôt que de migrer des données de test.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_clean_orphan_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Supprime les anciennes données de test
        migrations.RunSQL(
            "DELETE FROM api_messagechat CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DELETE FROM api_conversationcommande_participants CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "DELETE FROM api_conversationcommande CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # Supprime les anciens champs
        migrations.RemoveConstraint(
            model_name='conversationcommande',
            name='unique_conversation_per_order',
        ) if False else migrations.RunSQL(
            "ALTER TABLE api_conversationcommande DROP CONSTRAINT IF EXISTS unique_conversation_per_order;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        
        migrations.RemoveField(
            model_name='conversationcommande',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='conversationcommande',
            name='commande',
        ),

        # Ajoute les nouveaux champs
        migrations.AddField(
            model_name='conversationcommande',
            name='commande',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='conversations', to='api.commande',
            ),
        ),
        migrations.AddField(
            model_name='conversationcommande',
            name='participant_a',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='conversations_a', to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='conversationcommande',
            name='participant_b',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='conversations_b', to=settings.AUTH_USER_MODEL,
            ),
        ),

        # Rend les champs NOT NULL
        migrations.RunSQL(
            "ALTER TABLE api_conversationcommande ALTER COLUMN commande SET NOT NULL;",
            reverse_sql="ALTER TABLE api_conversationcommande ALTER COLUMN commande DROP NOT NULL;",
        ),
        migrations.RunSQL(
            "ALTER TABLE api_conversationcommande ALTER COLUMN participant_a SET NOT NULL;",
            reverse_sql="ALTER TABLE api_conversationcommande ALTER COLUMN participant_a DROP NOT NULL;",
        ),
        migrations.RunSQL(
            "ALTER TABLE api_conversationcommande ALTER COLUMN participant_b SET NOT NULL;",
            reverse_sql="ALTER TABLE api_conversationcommande ALTER COLUMN participant_b DROP NOT NULL;",
        ),

        # Ajoute la contrainte UNIQUE
        migrations.AddConstraint(
            model_name='conversationcommande',
            constraint=models.UniqueConstraint(
                fields=('commande', 'participant_a', 'participant_b'),
                name='unique_conversation_par_paire',
            ),
        ),
    ]

